### ISSUE TITLE
Issue with export function

### ISSUE THREAD

**Issue by gpythomas** [Arborator/arborator-server#12]
I noticed an issue with the conll export function in the last commit of Arborator (17-10-08). After updating my installation to this last commit, I was unable to export conll trees properly; conll files were exported but the exported files in the export folder lacked dependency information. All other fields where correctly exported, included the conll comments. 

The problem appears to be with the definition of the function conllSentenceExport in database.py. Using the function definition from before the last commit allowed me to export the files with the dependency information. However, the old version does not export the conll comments.

In addition, while exporting individual trees (e.g. in pdf or svg) from the editor window, I encountered this error:

[convert_svg.cgi.pdf](https://github.com/kimgerdes/arborator/files/1395496/convert_svg.cgi.pdf)

This is solved by creating a "cache" folder in arborator/export. I am not sure if I missed something during the installation of arborator or if this folder should be included in the source dump.

**Comment by kimgerdes** [comment]
please try the newest version. i think it's fixed now.
the new export can also export other features into conllu format and sentence features (ids, translations, ...) into comment lines before each sentence.
