### ISSUE TITLE
Question: editing project properties

### ISSUE THREAD

**Issue by amir-zeldes** [Arborator/arborator-server#18]
Hi, I just upgraded to the latest master and noticed that inside a project, the thing black bar at the bottom where we could enter project configuration and e.g. edit relations/labels available in the project is gone. 

Does anyone know how we can access this functionality in the latest version?

**Comment by kimgerdes** [comment]
hello, this bar is only there if you're admin. it should still be there if you have an admin account.

**Comment by amir-zeldes** [comment]
My user file says this:

```
admin = 3# admin level, currently should be 0 or 3
```

And I think I should be able to see at least 'you are logged in as ...', even if I'm not admin. Currently the black bar is completely missing once I'm inside a project. 

If I'm on the main project selection page I can see a black bar, saying:

```
logged in as Zeldes    logout    edit the account Zeldes    User Administration
```

But it is gone if I'm inside the project... Any ideas what could be causing this?

**Comment by amir-zeldes** [comment]
OK, I figured it out:

  * I upgraded from an older arborator and in the DB, the parser user has realname set to NULL
  * This line lower cases all users' real names to sort, but this fails on NULL:
    * https://github.com/Arborator/arborator-server/blob/stable/project.cgi#L728
  * As a result, the entire menu portion is not printed

I should be able to fix this for backwards compatibility purposes.

**Comment by amir-zeldes** [comment]
@kimgerdes - I'm in the arborator organization now but can't push directly to the repo. Would you be willing to invite me with push rights? It could simplify the PR process if you're OK with it.

**Comment by kimgerdes** [comment]
Great that you found it, thanks!
Marine and me have been discussing and trying to reproduce the bug without success.
You should have push rights now.
