### ISSUE TITLE
Python 2.6 incompatible syntax in lib/treebankfiles.py

### ISSUE THREAD

**Issue by amir-zeldes** [Arborator/arborator-server#24]
The double `with` statement here crashes on Python 2.6:

https://github.com/Arborator/arborator-server/blob/stable/lib/treebankfiles.py#L1303

This is important for servers running RHEL, which comes with Python 2.6 by default.

**Comment by kimgerdes** [comment]
right. it should be embedded using an extra `with`.
can you do that?

**Comment by amir-zeldes** [comment]
Sure. You want everything committed directly to stable, right?

**Comment by kimgerdes** [comment]
yes please :/
we are waiting for the new flask version. new deadline for the programmer may 25...
