### ISSUE TITLE
For some annotations, all tokens show up in annotation view as "undefined"

### ISSUE THREAD

**Issue by nschneid** [Arborator/arborator-server#3]
No dependency arcs are showing up (it's unclear if the user has been able to annotate any). The POSes are intact, though. And other users' annotations for the sentence show up fine.
<img width="814" alt="undefined" src="https://cloud.githubusercontent.com/assets/985263/15648245/160ada4a-2661-11e6-8618-9332dffca917.png">

**Comment by nschneid** [comment]
This is in Firefox 46.0.1.

**Comment by kimgerdes** [comment]
i have not seen that.
is that on all trees of the sample or just one? on all the samples of the same user?
to see where this is happening, you could check with firebug (net tab) what is actually sent from the server when you open and close a tree.
one simple workaround might be to remove the "omri" tree (clicking on the small "x" above the name) and then the user recreates it.

**Comment by nschneid** [comment]
It seems to be just that sentence, which is the first in the dataset. I think it happened to me once when I tried to annotate this sentence? I did try deleting the user's annotation and having him redo it, but that didn't work.

Here's the buggy behavior: the `"t"` field seems to be missing from the response JSON:
<img width="1273" alt="arborator-firebug" src="https://cloud.githubusercontent.com/assets/985263/15800388/4fce2838-2a6f-11e6-8b15-5aeda2365e26.png">

And here's my annotation of the same sentence:
<img width="1275" alt="arborator-firebug2" src="https://cloud.githubusercontent.com/assets/985263/15800394/669408f8-2a6f-11e6-9286-8f12a9019e8d.png">

**Comment by kimgerdes** [comment]
mmmh. strange: the trees of one user don't get initiated at the first iteration, but for the following trees, it works.
to help me direct my debugging:
are you in some kind of exo mode for this sample?
in your configuration, have you defined these values:
importAnnotatorName     =   prof # edit only before entering texts into the database
teacher =   prof 
exoBaseAnnotatorName    =   x # name of user that should serve as the base for the student to start her tree
?
is the user supposed to annotate the whole sample or have you done some distribution of sentences?

**Comment by nschneid** [comment]
> are you in some kind of exo mode for this sample?

No, I don't know how to use the exo modes.

> in your configuration, have you defined these values:
> importAnnotatorName = prof # edit only before entering texts into the database
> teacher = prof
> exoBaseAnnotatorName = x # name of user that should serve as the base for the student to start her tree
> ?

I left the defaults:

```
importAnnotatorName =   parser
baseAnnotatorName       =   parser
```

No `teacher` or `exoBaseAnnotatorName`.

> is the user supposed to annotate the whole sample or have you done some distribution of sentences?

I assigned the entire sample to the user. Is there a way to assign only particular sentences?

**Comment by kimgerdes** [comment]
> No, I don't know how to use the exercise modes.

yeah, that should be explained somewhere:
- teacher visible mode: dumb exercise where students have to copy the teacher's tree which is visible but not directly modifiable. a good start with 3 sentences or so.
- no feedback: the student can't see the teacher's tree and gets no feedback, but the admin can export the results of the students' annotations compared to the teacher trees
- percentage: when students save, they can see how many percent they got wrong of dependencies and pos, but they don't know where
- graphical feedback: when students save, they can see where there are problems compared to the teacher's tree and they have to find the right annotation.

> baseAnnotatorName       =   parser

**baseAnnotatorName** is no longer used. to make it clearer that this is important only for exercise modes the variable is called **exoBaseAnnotatorName**. it is the name of the user that provides the tree that the student should start with.
**teacher** is used for comparisons and results in exercises.

> I assigned the entire sample to the user. Is there a way to assign only particular sentences?

yes, but not from the graphical interface. there's code to intelligently distribute new sentences mixed up with already annotated sentences in a way that two students don't have the same set of sentences to annotate. this is used to class-source dependency annotation...

but that doesn't solve your problem.

so how does omri go about to recreate that tree once you erased it? he looks at the parser tree, modifies it and saves it? at which point does the tree disappear? when he closes and reopens it?

**Comment by nschneid** [comment]
I'll ask him exactly when it started appearing as undefined.

**Comment by nschneid** [comment]
This was a major problem for some students using Georgetown's Arborator installation recently. It seemed to be that when they hit save for an annotation, it occasionally would save the tokens as undefined even though they were correct in the original (parser output). To get the actual tokens back, one could double-click on each and edit the token metadata, or delete the annotation and create a new one.

This happened intermittently and was thus difficult to debug, but I suspect it is an issue where there is an AJAX request to save the annotation and the tokens cannot be accessed when preparing the data for that request (hence, undefined).

**Comment by kimgerdes** [comment]
i still haven't seen that but i think that there might be an issue with the definition of the latest active svg when saving.
in the new version it should be visually indicated which is the currently edited tree. we'll try to do that...
