### ISSUE TITLE
Is there a way to mark a node as the root of the sentence?

### ISSUE THREAD

**Issue by nschneid** [Arborator/arborator-server#5]
I've just been leaving the root node unattached, but in the exported CoNLL, it is then `_` rather than `0`.

**Comment by nschneid** [comment]
Not working for me: (ignore the first few seconds of the animation)

![arborator](https://cloud.githubusercontent.com/assets/985263/15804783/82fe0a78-2b0c-11e6-8778-57c073950eed.gif)

**Comment by kimgerdes** [comment]
is it working on http://arborator.ilpga.fr/q.cgi ?

**Comment by nschneid** [comment]
Yep.

**Comment by nschneid** [comment]
Also works in the quick editor for the installation I'm using (@amir-zeldes's).

**Comment by kimgerdes** [comment]
have you tried letting it go when your mouse pointer is close to the upper edge of the drawing area?

if yes, maybe you can try a higher value of the following parameter in your project's config file?
rootTriggerSquare = 50; // distance from top of svg above which root connections are created and minimum width of this zone (from 0 to 50 par example the connection jumps to the middle)

**Comment by nschneid** [comment]
I set `rootTriggerSquare = 80`, and now it works. Doesn't actually change color, but if I drag the mouse high enough and release it, I get the relation dropdown.

**Comment by kimgerdes** [comment]
great that you got it working!
